---
- name: creating mysql user (medium_post)
  mysql_user:
    name: "{{ db_user }}"  
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: creating medium_db
  mysql_db:
    name: "{{ db_name }}"
    state: present